# Generated by Django 5.0.3 on 2024-05-13 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_defense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('link_call', models.CharField(max_length=200)),
                ('exspert1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Expert1', to=settings.AUTH_USER_MODEL)),
                ('exspert2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Expert2', to=settings.AUTH_USER_MODEL)),
                ('exspert3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Expert3', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Project', to='home.project')),
            ],
        ),
    ]
