# Generated by Django 5.0.3 on 2024-05-13 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_project_defense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_defense',
            name='exspert1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Expert1_project_defense', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project_defense',
            name='exspert2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Expert2_project_defense', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project_defense',
            name='exspert3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Expert3_project_defense', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project_defense',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Project_project_defense', to='home.project'),
        ),
        migrations.CreateModel(
            name='Content_points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('link_anti_plagiarism', models.CharField(max_length=200)),
                ('exspert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Expert_content_points', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Project_content_points', to='home.project')),
            ],
        ),
    ]
