# Generated by Django 5.0.3 on 2024-05-13 23:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_project_defense_exspert1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Content_points',
            new_name='Content_point',
        ),
    ]
